### ISSUE TITLE
Style_checker is finding errors in Willims code😬

### ISSUE THREAD

**Issue by liam7973** [DylanKirbs/ampl-tests#15]
![image](https://github.com/DylanKirbs/ampl-tests/assets/127299363/737b9561-8c41-4e77-91ff-6a0cb4a03219)

**Comment by DylanKirbs** [comment]
Currently the style_checker uses a line by line regeneration based approach, so it is context-free.

Although I may remove the one check for no bracket before else

**Comment by DylanKirbs** [comment]
Currently the style_checker uses a line by line regeneration based approach, so it is context-free.

Although I may remove the one check for no bracket before else
