### ISSUE TITLE
Parser same output poll

### ISSUE THREAD

**Issue by ZOfficial07** [DylanKirbs/ampl-tests#18]
If you get different output compared to the 0.ampl file in the parser dir then leave a comment with your output

If you get the same output leave a comment confirming you got the same output

**Comment by MatthewStein02** [comment]
Mine differs. I got: 
<program> at 1:1.
  <body> at 3:5.
    <statements> at 3:5.
    </statements> at 3:11.
  </body> at 3:11.
</program> at 3:11.
Success!

**Comment by MatthewStein02** [comment]
Mine differs. I got:
"<program> at 1:1.
  <body> at 3:5.
    <statements> at 3:5.
    </statements> at 3:11.
  </body> at 3:11.
</program> at 3:11.
Success!"

**Comment by MatthewStein02** [comment]
file:///home/matthew/Documents/0.out

**Comment by MatthewStein02** [comment]
Mine differs. I am unable to post my output because github removes anything within the arrows. Just imagine there were arrows around program, body and statements.
program at 1:1.
  body at 3:5.
    statements at 3:5.
    /statements at 3:11.
  /body at 3:11.
/program at 3:11.
Success!

**Comment by DylanKirbs** [comment]
```
Test
```

**Comment by willieloea** [comment]
Mine is the same as @MatthewStein02's

**Comment by ZOfficial07** [comment]
So for you guys it reports the position at the start of the tokens, but for mine it reports it at the end of the tokens, interesting

**Comment by ZOfficial07** [comment]
The token is a look ahead variable so in sense it should always be one token ahead but I'm really not sure. Did you guys modify the main or/and parse_program functions at all?

**Comment by ZOfficial07** [comment]
I changed one line of code mine is now the same as yours

**Comment by DylanKirbs** [comment]
> I changed one line of code mine is now the same as yours, except mine says the last line is 3:12(everywhere where yours says 3:11) which I assume is the index of the eof char.

I also get 3:12

**Comment by DylanKirbs** [comment]
I'm closing this issue, for future reference please refer to #21
