### ISSUE TITLE
Parser Test Output & EOL character position

### ISSUE THREAD

**Issue by ZOfficial07** [DylanKirbs/ampl-tests#21]
Leave a comment with your output for test 76 if you differ.
If you get the same output leave a confirmation comment.

**Comment by DylanKirbs** [comment]
I get the same output :muscle:

**Comment by MatthewStein02** [comment]
I got the same except instead of 5:1, I'm getting 4:33. I understan you have an EOF character that mine doesn't but I'm not sure if that should be included. The ampl file only has 4 lines so it doesn't make sense to get output on line 5.

**Comment by KellenMossner** [comment]
I get the same :)

**Comment by Eubo0** [comment]
I'm getting the same as well

**Comment by willieloea** [comment]
Mine differs:
<           </arglist> at 4:33.
<         </call> at 4:33.
<       </statement> at 4:33.
<     </statements> at 4:33.
<   </body> at 4:33.
< </program> at 4:33.
---
>           </arglist> at 5:1.
>         </call> at 5:1.
>       </statement> at 5:1.
>     </statements> at 5:1.
>   </body> at 5:1.
> </program> at 5:1.

My source file did not have a 5th line, so unless yours did, I would like to know why those should have a position on the next line.

**Comment by DylanKirbs** [comment]
> I got the same except instead of 5:1, I'm getting 4:33. I understan you have an EOF character that mine doesn't but I'm not sure if that should be included. The ampl file only has 4 lines so it doesn't make sense to get output on line 5.

Honestly makes sense, I'll look into it

**Comment by DylanKirbs** [comment]
Ok, I'm interested to hear your feedback, but printing each character one at a time gives me the following:

The code to reproduce this output:
```c
/* In next_char */
printf("ASCII: #%d\n", ch);
```

A reminder of the last line of *76.ampl*:
```
stellies(true)
```

```
ASCII: #41
ASCII: #10
ASCII: #-1
```

This equates to the closing parenthesis (41) followed by a newline (10) then EOF (-1), but in *vim* I don't see the newline.
So according to my scanner, the EOF **should** be reported on 5:1

**Comment by DylanKirbs** [comment]
From this, I'm happy to conclude that it should be reported on line 4:
![image](https://github.com/DylanKirbs/ampl-tests/assets/58003289/4d1ca46d-9fff-49b3-9b25-97ab8da6ba09)

This can be achieved using `abort_cp`

**Comment by DylanKirbs** [comment]
Please update the test cases to reflect your output.

Run `test.py parser --side-by-side #testnum` to ensure that the rest of your output is consistent with the provided output.
You can make use of `./create_test_cases parser #testnum` if your output is complete and in-line with the rest of the output.||

Then create a PR and assign @DylanKirbs to it and link to this issue, I will then review and merge the changes, as well as close the issue.

> Please make note of the most recent merge #23  and the comments on the <"else"> section.

**Comment by DylanKirbs** [comment]
This has been brought up to Willem, see the [teams post](https://teams.microsoft.com/l/message/19:d66fa4a27f274131821dd53d4f294352@thread.tacv2/1692612856822?tenantId=a6fa3b03-0a3c-4258-8433-a120dffcd348&groupId=5263d6c7-b093-48ed-bbbd-dda5627bcc60&parentMessageId=1692612856822&teamName=RW244%20(2023)&channelName=AMPL%20Compiler%20Project&createdTime=1692612856822&allowXTenantAccess=false).
