### ISSUE TITLE
Trigger happy style checker

### ISSUE THREAD

**Issue by Eubo0** [DylanKirbs/ampl-tests#22]
This is amusing, but isn't urgent at all. The style checker seems to recognise parts of function names as control statements.

![image](https://github.com/DylanKirbs/ampl-tests/assets/92365654/93c8c770-0eef-4367-9f70-688a479de39b)

**Comment by DylanKirbs** [comment]
I'm aware of it :laughing:
I'd rather it be more strict than less

**Comment by DylanKirbs** [comment]
I'll see what I can do to update the **REXEG** for the _<control_statement...>_ rules

**Comment by DylanKirbs** [comment]
I've pushed a fix, it should be merged soon
