### ISSUE TITLE
Hidden characters and parsing else

### ISSUE THREAD

**Issue by MatthewStein02** [DylanKirbs/ampl-tests#24]
I have noticed that some ampl files might have hidden EOF characters, specifically in 0.ampl and 12.ampl. When I retype the last few characters my line position changes even though the text is identical. My other issue is 12.ampl, 77.ampl and 78.ampl are parsing else which isn't in the ebnf.

**Comment by DylanKirbs** [comment]
![image](https://github.com/DylanKirbs/ampl-tests/assets/58003289/285e6fe1-320c-4777-97f7-f2a022e2a806)
The `<else>` and `<elif>` tags are done making use of `DBG_info` in accordance with this. This is just to facilitate ease of debugging more complex structures and unreachable code later on.

As for the EOF character issue, please refer to issue #21
