### ISSUE TITLE
Errors not detected

### ISSUE THREAD

**Issue by WilkieZA** [DylanKirbs/ampl-tests#47]
Rule 13 for when the additive operator is used inside brackets. For example malloc(n+1) was not detected by the style checker.

Rule 18 for indentation done before comments. (So basically a line containing only comments but the comment is indented by spaces and not tabs)

Rule 4 where the case statement does not align with the switch keyword. (I don't know how this should be checked though, because mine was indented by 1 tab, but I lost style marks for it)

**Comment by DylanKirbs** [comment]
The unfortunate reality is that the style checker is implemented using Regular Expressions to check for rules on a line by line basis.

It would probably need a massive overhaul or a lot of extra conditional logic to handle these cases.

And I don't have the time to do this at the moment
