### ISSUE TITLE
Key overwrites are not to spec

### ISSUE THREAD

**Issue by liam7973** [DylanKirbs/ampl-tests#48]
As we get given the error code for duplicate keys in hashtable.h:
`/* --- error return codes --------------------------------------------------- */`
`#define HASH_TABLE_KEY_VALUE_PAIR_EXISTS -1`
`#define HASH_TABLE_NO_SPACE_FOR_NODE     -2`

As well as the instructions to return one of the designated error codes if insertion fails (in the documentation for ht_insert found in hashtable.h), it seems that key overwrites are not meant to be used.

**Comment by DylanKirbs** [comment]
To the best of my knowledge, it is an important feature of a Hadham table to be able to update the value associated with a key.

The error code being `HASH_TABLE_KEY_VALUE_PAIR_EXISTS` is somewhat suggestive that it should report when the key and value exist.

My initial implementation was in line with your suggestion, but upon further review and consultation with other students, it was changed.

This, however, can be easily changed to reflect either point of view.

Therefore, it may be worthwhile confirming what the requirements are via Willem.

**Comment by DylanKirbs** [comment]
![image](https://github.com/DylanKirbs/ampl-tests/assets/58003289/d281e770-4f6e-48e0-94d6-c72679e2864e)

Header from the symboltable
