### ISSUE TITLE
Use of offset in symbol table tests.

### ISSUE THREAD

**Issue by DylanKirbs** [DylanKirbs/ampl-tests#51]
Upon review, it seems as though the offset in the symbol table tests, have been misleadingly used.
![image](https://github.com/DylanKirbs/ampl-tests/assets/58003289/31f2c09a-aff0-4d14-bd1e-b26cf2e2e217)

When refactoring some of the symbol table code and reviewing this particular `TODO`: 
![image](https://github.com/DylanKirbs/ampl-tests/assets/58003289/3d7d391d-3787-4e82-8f94-aca42a49d8c0)
It came to my attention that this is most likely referring to the `prop->offset` pointer.

It is my understanding that each of the subroutines should report the offset of each of its variables starting from 1, including the main. Due to the way the EBNF is defined, the subroutines **must** occur before the *main* method of the program, thus, the offset should be reset to 1 after a subroutine is closed.

Example of a program with the subroutines `a` and `d`.
**Table for `a`**
| ID | Type | Offset |
| --- | :--- | ---: |
| b | variable | 1 |
| c | variable | 2 |

**Table for `b`**
| ID | Type | Offset |
| --- | :--- | ---: |
| e | variable | 1 |

**Main Table**
| ID | Type | Offset |
| --- | :--- | ---: |
| a | callable | NA |
| d | callable | NA |
| f | variable | 1 |
| g | variable | 2 |

The implementation of `testsymboltable` simply increments the offset for each variable resulting in, `e` being 3, `f` being 4, and `g` being 5.

**Comment by Eubo0** [comment]
I think the offset in user defined subroutines starts from 0 as one might expect. But in main it starts from 1 because the target is JASMIN & that will have “String[] args” taking up offset 0 in main.

**Comment by DylanKirbs** [comment]
> I think the offset in user defined subroutines starts from 0 as one might expect. But in main it starts from 1 because the target is JASMIN & that will have “String[] args” taking up offset 0 in main.

I think you may have misunderstood me, the offset always starts from 1 for code generation. But the `testsymboltable` does not "reset" the offset after subroutines.

**Comment by Eubo0** [comment]
> > I think the offset in user defined subroutines starts from 0 as one might expect. But in main it starts from 1 because the target is JASMIN & that will have “String[] args” taking up offset 0 in main.
> 
> I think you may have misunderstood me, the offset always starts from 1 for code generation. But the `testsymboltable` does not "reset" the offset after subroutines.

My bad. Yeah, looks like it’s using its own offset instead about what’s in the table.

There is a Jasmin directive E.g. “.limit locals 10” that limits the size of the local variable array. My best guess is since the TODO references codegen, it’s something to do with that.

**Comment by DylanKirbs** [comment]
My issue is that when implementing this for type checking it creates conflict with the existing symbol table test cases.

Here is the diff for case 0 of the symboltable.
![image](https://github.com/DylanKirbs/ampl-tests/assets/58003289/1eb5e4b9-b563-4f5c-a740-2bdf77c8f561)

**Comment by SeanEvL** [comment]
My personal opinion is that the testcases are incorrect and that he other way of doing it is the correct way.
In the spec it says that no global variables are allowed (pg41 or 45/68).
This means to me that the only way an id may be called that hasn't been defined locally or is a parameter of the current subroutine is: if it is a previously defined subroutine. 
Subroutines also don't have an offset number.
This way the offset should reset every time a new subroutine is created. as variables inside the global symboltable (which should only be subroutines) don't have an offset.
It doesn't feel right to not reset the offset, especially with him saying inside the skeleton for open_subroutine: "and reset the current offset".

**Comment by DylanKirbs** [comment]
Yeah, you can see my most recent version does not coincide with the older versions. So what I'll do is create a new branch for this and allow it to be publicly reviewed before merging.

**Comment by DylanKirbs** [comment]
I've create a PR to fix this, but I want it to be checked out first.
